version: "3" 

services:
  golf_backend:
    build: .
    container_name: "golf_backend"
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: always

networks:
  default:
    name: proxy
    external: true
