services:
  mongo:
    container_name: "golf_database"
    restart: always
    image: mongo:latest
    ports:
      - "3001:27017"
    volumes:
      - db:/home/puttnation_db
    networks:
      - proxy

  golf_backend:
    container_name: "golf_backend"
    build: .
    image: golf_backend:latest
    ports:
      - "3002:80"
    restart: always
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://golf_database:27017/puttnation_db"
    networks:
      - proxy

volumes:
  db:

networks:
  proxy:
    external: true
