version: "3" 

services:
  pub_golf_backend:
    build: .
    container_name: "pub_golf_backend"
    volumes:
      - ./pub_data:/app/data
    restart: always
    
  circus_golf_backend:
    build: .
    container_name: "circus_golf_backend"
    volumes:
      - ./circus_data:/app/data
    restart: always

networks:
  default:
    name: proxy
    external: true
