services:
  golf_database:
    container_name: golf_database
    restart: always
    image: mongo:latest
    ports:
      - "3001:27017"
    volumes:
      - db:/data/db
    networks:
      - proxy  # Ensure it joins the shared network

  golf_backend:
    container_name: golf_backend
    build: .
    image: golf_backend:latest
    ports:
      - "3002:80"
    restart: always
    depends_on:
      - golf_database
    environment:
      DATABASE_URL: "mongodb://golf_database:27017/puttnation_db"
    networks:
      - proxy  # Ensure it joins the shared network

volumes:
  db:

networks:
  proxy:
    external: true  # Use the shared network
